### ISSUE TITLE
ERC calculation

### ISSUE THREAD

**Issue by Jing25** [NCAR/fire-indices#3]
Hi,

I tried to use your script to calculate ERC. Here's the result:
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/27107288/91213459-7a6b8000-e6c6-11ea-97a0-05cc1ebe742f.png">
This is ERC at 2020-01-10. On the left is the "actual" image from gridMET (http://www.climatologylab.org/gridmet.html). On the right is the calculated one. 
I think my input files are correct, since the calculation for fm100 and fm1000 works well, and I double checked the units. But the result looks like where there's precipitation, the value there is lower than "actual". 

I'm wondering if it's because the calculation used in your script is different or I made a mistake somewhere. 

Thank you!
Jing

**Comment by akessenich** [comment]
Hi Jing,
I do have slightly different calculations than the gridMET version, and my version is more sensitive to precipitation. What you're observing here, (just looking at the images you provided) seems consistent with my testing. A few additional changes have been made in my code to reflect the updated ERC 2016 calculations, which are laid out here if you were curious: https://gacc.nifc.gov/eacc/predictive_services/fuels_fire-danger/documents/Overview%20of%20NFDRS2016%20and%20Implementation%20and%20Evaluation.pdf
Hope this helps! Please let me know if there is anything else I can help with.
Cheers,
Lee

**Comment by Jing25** [comment]
Great, thanks!
