### ISSUE TITLE
KBDI calculation

### ISSUE THREAD

**Issue by chjones2** [NCAR/fire-indices#5]
hello,
I noticed that in your calculation of the KBDI in the calc_kbdi.ncl routine line 113, the last term in the numerator is -0.83

However, I found this paper [chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/viewer.html?pdfurl=http%3A%2F%2Fpeople.atmos.ucla.edu%2Fycao%2Fpapers%2FComputer%2520Calculation%2520of%2520the%2520Keetch-Byram%2520Drought%2520Index-Programmers%2520Beware!.pdf&clen=335882&chunk=true](url)

and the author argues that it should -8.30, which is due to a typographical error in the original KBDI paper. 
Any ideas are greatly appreciated.

Cheers,

Charles Jones

**Comment by akessenich** [comment]
Hi Charles,
Thanks for bringing this to my attention. I based the code on the original 1968 paper, not the revised 1988 version (which does seem to be much more difficult to find than the original). I will go ahead and amend the code to have the -8.3 value instead of -0.83.
--Lee
