### ISSUE TITLE
Precipitation duration correction factor computation

### ISSUE THREAD

**Issue by plecntre** [NCAR/fire-indices#6]
Hello,

I was wondering how you managed to compute the correction factor for precipitation duration ('pdur_jolly_22i.nc') that you later use in 'cal_pduration.ncl'. I cannot find any link!

Also, where does come from the formula used in 'cal_pduration.ncl' for estimating the precipitation duration?

Thanks a lot for your help,

Pierre

**Comment by akessenich** [comment]
Hi Pierre,
The correction factor was not calculated by me, but was provided to me. It was originally calculated by Matt Jolly. The methodology is explained briefly in [this paper](https://www.mdpi.com/2571-6255/2/3/47) which expands upon gridded calculations of ERC and BI. It is explained in the materials and methods section.
Please let me know if you have any further questions.
Cheers,
Lee

**Comment by plecntre** [comment]
Hi Lee,

Thanks a lot for your answer, that helps a lot, I'll look at the paper!

I have another question: for computing the temperature and the relative humidity at the fuel-atmosphere interface (as done in `calc_erc.ncl` using the function `adjust(tmmprm, rhprm, sow)`, you are initializing:
 - `tmmprm` at `maxt -2`
 - `rhprm` at `rhmin + 2`

I don't see where this number `2` comes from (by comparing with the NFDRS basic equations by Cohen and Deeming (1985)). Would you know why it is like that?

Thanks again for your help,

Best,

Pierre

**Comment by akessenich** [comment]
Hi Pierre,
That particular bit of the code was adapted from John Abatzoglou, so I have no explanation for the exact number 2. However I can offer a qualitative answer. 
`tmmprm` and `rhprm` are supposed to be the temperature and humidity at 1 pm (1300). Around that time of day, it hasn't quite reached maximum temperature or minimum humidity, which I would guess is more around 3 pm. Therefore, go a couple degrees lower than maximum temperature and a few percentage points higher than minimum humidity when working with daily data.
Does that help?
Cheers,
Lee

**Comment by plecntre** [comment]
Hi Lee,

Yes that makes sense, thanks a lot for your help!

Best,

Pierre
