### ISSUE TITLE
error in fire-indices/calc_gsi.ncl

### ISSUE THREAD

**Issue by jackenvcan** [NCAR/fire-indices#7]
Hi,
Just wanted to note that, I think there's an error in normalizing the daylength value (line 26) of this code https://github.com/NCAR/fire-indices/edit/master/calc_gsi.ncl

Based of the work of [Jolly et al 2005](https://doi.org/10.1111/j.1365-2486.2005.00930.x)

Equation 3 has `iphoto= (ipho - iphoMin) / (iphoMax - iphoMin) = (ipho - 10) / (11-10)`
Base on this, I think line 26 should be `dayl = (daylit - 10.)`

**Comment by akessenich** [comment]
Hi, 
Apologies for the long delay on getting back to this issue. I will get back to you on this as soon as I am able to confirm one thing on the back end, as I did not directly adapt this from Jolly et al 2005.
Cheers,
Lee

**Comment by akessenich** [comment]
Thank you for pointing this out. It should just be `dayl = daylit - 10`
I will change the code accordingly.
Cheers,
Lee
